version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pg_mation_fastapi
    ports:
      - "5002:8000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/firebase-service-account.json
      - FIREBASE_STORAGE_BUCKET=pg-data-8c54e.appspot.com
    volumes:
      - ./src:/app/src
      - ./firebase-service-account.json:/app/firebase-service-account.json
    restart: unless-stopped
